// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiJihazV16floXPja2WhoAWiStRJOphuU',
    appId: '1:277430286884:web:705d8d5b43db57611cf6b1',
    messagingSenderId: '277430286884',
    projectId: 'women-safety-app-126e5',
    authDomain: 'women-safety-app-126e5.firebaseapp.com',
    storageBucket: 'women-safety-app-126e5.firebasestorage.app',
    measurementId: 'G-G7CL20LS12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYHrl_13wGHqlQXNsYLY4QYiVYgyD7R1M',
    appId: '1:277430286884:ios:6c9a7b8899a41eb81cf6b1',
    messagingSenderId: '277430286884',
    projectId: 'women-safety-app-126e5',
    storageBucket: 'women-safety-app-126e5.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYHrl_13wGHqlQXNsYLY4QYiVYgyD7R1M',
    appId: '1:277430286884:ios:6c9a7b8899a41eb81cf6b1',
    messagingSenderId: '277430286884',
    projectId: 'women-safety-app-126e5',
    storageBucket: 'women-safety-app-126e5.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiJihazV16floXPja2WhoAWiStRJOphuU',
    appId: '1:277430286884:web:7b34542a29e67e821cf6b1',
    messagingSenderId: '277430286884',
    projectId: 'women-safety-app-126e5',
    authDomain: 'women-safety-app-126e5.firebaseapp.com',
    storageBucket: 'women-safety-app-126e5.firebasestorage.app',
    measurementId: 'G-5WZHQ4N9RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8z0FrYrZ_T-L5bndEGq0njtc1qr_yZ9Y',
    appId: '1:277430286884:android:a0814a318eedfa931cf6b1',
    messagingSenderId: '277430286884',
    projectId: 'women-safety-app-126e5',
    storageBucket: 'women-safety-app-126e5.firebasestorage.app',
  );

}