name: women_safety_app
description: "A Women's Safety Flutter App with Firebase, Contacts, and Location Features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Essentials
  cupertino_icons: ^1.0.8
  flutter_sms: ^2.3.3
  url_launcher: ^6.1.14
  flutter_contacts: ^1.1.6
  permission_handler: ^11.4.0

  # Location & Map Utilities
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  location: ^8.0.0

  # Notifications
  flutter_local_notifications: ^19.0.0

  # Firebase Core & Auth
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0

  # HTTP for API requests (e.g., LocationIQ)
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/damini.png
    - assets/nirbhaya.png
    - assets/tejashwini.png
    - assets/family.png
    - assets/friends.png
    - assets/colleagues.png
    - assets/gps.png
