name: women_safety_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.0.0
# followed by an optional build number separated by a +.
version: 1.0.0+1

# Environment settings
environment:
  sdk: '>=3.6.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.4              # Latest resolvable
  permission_handler: ^11.4.0
  flutter_sms: ^2.3.3
  #telephony: ^0.2.0
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.1.6
  flutter_contacts: ^1.1.9+2
  async: 2.12.0

  permission_handler_android: 12.1.0  # Updated version
  fake_async: 1.3.2 # Updated version
  leak_tracker: 10.0.8  # Updated version
  material_color_utilities: ^0.11.1  # Updated version
  vm_service: 14.3.1  # Updated version

  geocoding: ^3.0.0
  location: ^8.0.0
  http: ^1.3.0                 # For API calls to LocationIQ
  firebase_auth: ^5.5.2
  #flutter_local_notifications: ^19.0.0
  #url_launcher: ^6.1.11
  #geolocator: ^13.0.3

# Dev dependencies for testing and linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#dependency_overrides:
  #firebase_auth_platform_interface: ^7.0.5
# Flutter-specific configuration
flutter:
  # Ensures that Material Icons are available
  uses-material-design: true
  #assets:
    #- assets/google.png
  # Add assets for images, icons, etc.
  #assets:
   # - lib/resources/assets/
